same_wechat_oauth:
    path:     /same/wechat/oauth/{type}
    defaults: { _controller: SameWechatBundle:Wechat:oauth }

same_wechat_homepage:
    path:     /same/wechat/index
    defaults: { _controller: SameWechatBundle:Wechat:index }

same_wechat_callback:
    path:     /same/wechat/callback
    defaults: { _controller: SameWechatBundle:Wechat:callback}

same_wechat_islogin:
    path:     /same/wechat/islogin
    defaults: { _controller: SameWechatBundle:Wechat:islogin }

same_wechat_jssdk:
    path:     /same/wechat/jssdk
    defaults: { _controller: SameWechatBundle:Wechat:jssdk }

same_wechat_tempalte:
    path:     /same/wechat/tempalte/{openid}
    defaults: { _controller: SameWechatBundle:Wechat:tempalte }

same_wechat_subscribed:
    path:     /same/wechat/subscribed/{openid}
    defaults: { _controller: SameWechatBundle:Wechat:subscribed }

same_wechat_test:
    path:     /same/wechat/test
    defaults: { _controller: SameWechatBundle:Wechat:test }

# same_wechat_refrence:
#     path:     /same/wechat/reflash/7dc132fe47aa1b8f34df58a24053e33a
#     defaults: { _controller: SameWechatBundle:Wechat:refrence }