services:
#    same_wechat.example:
#        class: Same\Bundle\WechatBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    same.wechat:
       class: Same\Bundle\WechatBundle\Model\Wechat
       arguments: [@service_container, @same.memcached]
    same.memcached:
       class: Memcached
       calls:
            - [ addServer, [ %memcached_host%, %memcached_port% ]]
