loreal_menexpert:
    resource: "@LorealMenexpertBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@SameAdminBundle/Resources/config/routing.yml"
    prefix:    /