loreal_menexpert_homepage:
    path:     /interaction
    defaults: { _controller: LorealMenexpertBundle:Interaction:index }

loreal_menexpert_error:
    path:     /interaction/error
    defaults: { _controller: LorealMenexpertBundle:Interaction:error }

loreal_menexpert_success:
    path:     /interaction/success
    defaults: { _controller: LorealMenexpertBundle:Interaction:success }

loreal_menexpert_main:
    path:     /interaction/main
    defaults: { _controller: LorealMenexpertBundle:Interaction:main }