loreal_menexpert_homepage:
    path:     /invitation
    defaults: { _controller: LorealMenexpertBundle:Invitation:index }

loreal_menexpert_index:
    path:     /invitation/index
    defaults: { _controller: LorealMenexpertBundle:Invitation:index }

loreal_menexpert_error:
    path:     /invitation/error
    defaults: { _controller: LorealMenexpertBundle:Invitation:error }

loreal_menexpert_success:
    path:     /invitation/success
    defaults: { _controller: LorealMenexpertBundle:Invitation:success }

loreal_menexpert_main:
    path:     /invitation/main
    defaults: { _controller: LorealMenexpertBundle:Invitation:main }

loreal_menexpert_interaction:
    path:     /invitation/interaction
    defaults: { _controller: LorealMenexpertBundle:Invitation:interaction }

loreal_menexpert_interactionhome:
    path:     /interaction
    defaults: { _controller: LorealMenexpertBundle:Interaction:index }

loreal_menexpert_api_check:
    path:     /api/check
    defaults: { _controller: LorealMenexpertBundle:Api:check }